import Head from "next/head";
import LoginForm from "@/components/LoginForm";



export default function Login() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
          <LoginForm/>  
    </>
  );
}
