import Head from "next/head";
import SideBar from "@/components/SideBar";
import ConsultarModelagens from "@/components/ConsultarModelagens";
import style from "@/styles/Home.module.css";



export default function Modelagens() {
  return (
    <>
      <Head>
        <title>Modelagens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
        <div className = {style.wrapperFormulario}>
          <SideBar/>
            <main className ={style.formularioConsulta}>
            <ConsultarModelagens/>
            </main>
        </div>
    </>
  );
}
