import Head from "next/head";
import SideBar from "@/components/SideBar";
import style from "@/styles/Home.module.css";
import UserProfile from "@/components/UserProfile"


export default function Perfil() {
  return (
    <>
      <Head>
        <title>Perfil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
           <div className = {style.wrapperProfile}>
          <SideBar/>
            <main className ={style.cardPerfil}>
            <UserProfile/>
            </main>
        </div>
    </>
  );
}
