import Head from "next/head";
import SideBar from "@/components/SideBar";
import style from "@/styles/Home.module.css";
import ConsultarQuizzes from "@/components/ConsultarQuizzes";



export default function Quizzes() {
  return (
    <>
      <Head>
        <title>Quizzes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
        <div className = {style.wrapperFormulario}>
          <SideBar/>
            <main className ={style.formularioConsulta}>
            <ConsultarQuizzes/>
            </main>
        </div>
    </>
  );
}
