import Head from "next/head";
import RegisterForm from "@/components/RegisterForm";



export default function Login() {
  return (
    <>
      <Head>
        <title>Cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <RegisterForm/>
    </>
  );
}
